#!/usr/bin/env python3
"""
CLINOVA 200+ AUTHENTIC MEDICINES & PHARMACY CATALOG
With verified Indian market MRP, discounted Clinova prices, manufacturers, categories, and dosages.
"""

MEDICINES_DB = [
    # ------------------------------------------------------------------------
    # 1. FEVER, PAIN & HEADACHE (18 items)
    # ------------------------------------------------------------------------
    {"id": "med_001", "name": "Dolo 650 Tablet", "category": "Fever & Pain Relief", "manufacturer": "Micro Labs Ltd", "mrp": 34, "price": 28, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets (Paracetamol 650mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_002", "name": "Crocin Advance 500mg", "category": "Fever & Pain Relief", "manufacturer": "GSK Healthcare", "mrp": 25, "price": 20, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets (Paracetamol 500mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_003", "name": "Combiflam Tablet", "category": "Pain & Muscle Relief", "manufacturer": "Sanofi India", "mrp": 46, "price": 38, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 20 tablets (Ibuprofen 400mg + Paracetamol)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_004", "name": "Calpol 500 Tablet", "category": "Fever & Pain Relief", "manufacturer": "GlaxoSmithKline", "mrp": 22, "price": 18, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_005", "name": "Zerodol-SP Tablet", "category": "Severe Pain & Swelling", "manufacturer": "Ipca Laboratories", "mrp": 128, "price": 102, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Aceclofenac + Paracetamol + Serratiopeptidase)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_006", "name": "Meftal-Spas Tablet", "category": "Abdominal & Period Pain", "manufacturer": "Blue Cross Labs", "mrp": 55, "price": 44, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Mefenamic Acid + Dicyclomine)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_007", "name": "Voveran SR 100mg", "category": "Arthritis & Joint Pain", "manufacturer": "Novartis India", "mrp": 185, "price": 149, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Diclofenac SR)", "inStock": True, "deliveryMins": 10, "icon": "🦴"},
    {"id": "med_008", "name": "Saridon Tablet", "category": "Headache & Migraine", "manufacturer": "Piramal Healthcare", "mrp": 42, "price": 36, "discount": "14% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Triple active formula)", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_009", "name": "Ultracet Tablet", "category": "Severe Post-Op Pain", "manufacturer": "Janssen / J&J", "mrp": 260, "price": 215, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Tramadol + Paracetamol)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_010", "name": "Volini Joint & Muscle Spray", "category": "Pain Relief", "manufacturer": "Sun Pharma", "mrp": 160, "price": 135, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 spray bottle of 55g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_011", "name": "Moov Pain Relief Ointment", "category": "Pain Relief", "manufacturer": "Reckitt Benckiser", "mrp": 150, "price": 128, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 tube of 50g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_012", "name": "Crocin 650 Tablet", "category": "Fever & Pain Relief", "manufacturer": "GSK Healthcare", "mrp": 32, "price": 26, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_013", "name": "Flexon Tablet", "category": "Body Ache & Sprain", "manufacturer": "Aristo Pharma", "mrp": 35, "price": 28, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets (Ibuprofen + Paracetamol)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_014", "name": "Diclogel Pain Relief Gel", "category": "Pain Relief", "manufacturer": "Dr. Reddy's Lab", "mrp": 95, "price": 78, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 tube of 30g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_015", "name": "Nise 100mg Tablet", "category": "Inflammation & Pain", "manufacturer": "Dr. Reddy's Lab", "mrp": 85, "price": 68, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Nimesulide 100mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_016", "name": "Hifenac-P Tablet", "category": "Joint & Swelling Pain", "manufacturer": "Intas Pharma", "mrp": 98, "price": 79, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Aceclofenac + Paracetamol)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_017", "name": "Ibugesic Plus Suspension", "category": "Children's Pain & Fever", "manufacturer": "Cipla Ltd", "mrp": 48, "price": 39, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml syrup", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_018", "name": "Zandu Balm Fast Action", "category": "Headache & Cold Balm", "manufacturer": "Emami Ltd", "mrp": 45, "price": 38, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 jar of 25ml", "inStock": True, "deliveryMins": 10, "icon": "🌿"},

    # ------------------------------------------------------------------------
    # 2. ANTIBIOTICS & ANTI-INFECTIVES (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_019", "name": "Augmentin 625 Duo Tablet", "category": "Antibiotics", "manufacturer": "GSK Pharmaceuticals", "mrp": 224, "price": 185, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Amoxicillin + Clavulanic Acid)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_020", "name": "Azithral 500 Tablet", "category": "Antibiotics", "manufacturer": "Alembic Pharma", "mrp": 132, "price": 108, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 5 tablets (Azithromycin 500mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_021", "name": "Taxim-O 200 Tablet", "category": "Antibiotics", "manufacturer": "Alkem Laboratories", "mrp": 195, "price": 158, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Cefixime 200mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_022", "name": "Cifran 500 Tablet", "category": "Antibiotics", "manufacturer": "Sun Pharma", "mrp": 48, "price": 39, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Ciprofloxacin 500mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_023", "name": "Moxikind-CV 625", "category": "Antibiotics", "manufacturer": "Mankind Pharma", "mrp": 190, "price": 152, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Amoxycillin + Pot Clavulanate)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_024", "name": "Zifi 200 Tablet", "category": "Antibiotics", "manufacturer": "FDC Limited", "mrp": 115, "price": 94, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Cefixime 200mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_025", "name": "Zenflox 200 Tablet", "category": "Antibiotics", "manufacturer": "Mankind Pharma", "mrp": 88, "price": 72, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Ofloxacin 200mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_026", "name": "Oflox 200 Tablet", "category": "Antibiotics", "manufacturer": "Cipla Ltd", "mrp": 78, "price": 64, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Ofloxacin)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_027", "name": "Azee 500 Tablet", "category": "Antibiotics", "manufacturer": "Cipla Ltd", "mrp": 130, "price": 106, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 5 tablets (Azithromycin)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_028", "name": "Cepodem 200 Tablet", "category": "Antibiotics", "manufacturer": "Ranbaxy / Sun Pharma", "mrp": 210, "price": 169, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Cefpodoxime Proxetil)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_029", "name": "Norflox 400 Tablet", "category": "Urinary Antibiotics", "manufacturer": "Cipla Ltd", "mrp": 84, "price": 68, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Norfloxacin 400mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_030", "name": "Metrogyl 400 Tablet", "category": "Amebic & Stomach Infection", "manufacturer": "J.B. Chemicals", "mrp": 24, "price": 19, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Metronidazole 400mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_031", "name": "Amoxyclav 625 Tablet", "category": "Antibiotics", "manufacturer": "Abbott Healthcare", "mrp": 215, "price": 175, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_032", "name": "Doxy-1 100mg Capsule", "category": "Antibiotics", "manufacturer": "USV Pvt Ltd", "mrp": 62, "price": 50, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 capsules (Doxycycline 100mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_033", "name": "Clavam 625 Tablet", "category": "Antibiotics", "manufacturer": "Alkem Laboratories", "mrp": 220, "price": 178, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_034", "name": "Monocef-O 200 Tablet", "category": "Antibiotics", "manufacturer": "Aristo Pharma", "mrp": 190, "price": 154, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Cefpodoxime)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_035", "name": "Levoflox 500 Tablet", "category": "Antibiotics", "manufacturer": "Cipla Ltd", "mrp": 105, "price": 85, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Levofloxacin 500mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_036", "name": "Oflomac 200 Tablet", "category": "Antibiotics", "manufacturer": "Macleods Pharma", "mrp": 75, "price": 61, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_037", "name": "Sporidex 500 Capsule", "category": "Antibiotics", "manufacturer": "Sun Pharma", "mrp": 170, "price": 139, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 capsules (Cephalexin 500mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_038", "name": "Bactrim DS Tablet", "category": "Antibiotics", "manufacturer": "Abbott India", "mrp": 28, "price": 23, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Trimethoprim + Sulfamethoxazole)", "inStock": True, "deliveryMins": 10, "icon": "💊"},

    # ------------------------------------------------------------------------
    # 3. ACIDITY, HEARTBURN & GASTROINTESTINAL (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_039", "name": "Pan-D Capsule", "category": "Acidity & Gas Relief", "manufacturer": "Alkem Laboratories", "mrp": 199, "price": 159, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 capsules (Pantoprazole 40mg + Domperidone 30mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_040", "name": "Pantocid 40 Tablet", "category": "Acidity & Gas Relief", "manufacturer": "Sun Pharma", "mrp": 165, "price": 134, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Pantoprazole 40mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_041", "name": "Razo-D Capsule", "category": "Acidity & Gas Relief", "manufacturer": "Dr. Reddy's Lab", "mrp": 210, "price": 168, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 capsules (Rabeprazole + Domperidone)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_042", "name": "Omez 20 Capsule", "category": "Acidity & Gas Relief", "manufacturer": "Dr. Reddy's Lab", "mrp": 62, "price": 49, "discount": "21% OFF", "prescriptionRequired": True, "dosage": "1 strip of 20 capsules (Omeprazole 20mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_043", "name": "Gelusil MPS Liquid (Mint)", "category": "Antacid & Heartburn", "manufacturer": "Pfizer Ltd", "mrp": 140, "price": 118, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 200ml antacid syrup", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_044", "name": "Digene Mint Flavour Gel", "category": "Antacid & Gas", "manufacturer": "Abbott Healthcare", "mrp": 155, "price": 129, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 200ml gel syrup", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_045", "name": "Rabekind-DSR Capsule", "category": "GERD & Reflux", "manufacturer": "Mankind Pharma", "mrp": 145, "price": 116, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 capsules", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_046", "name": "Eno Fruit Salt (Lemon)", "category": "Instant Acidity Relief", "manufacturer": "GSK Healthcare", "mrp": 160, "price": 139, "discount": "13% OFF", "prescriptionRequired": False, "dosage": "1 jar of 100g powder", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_047", "name": "Cremaffin Plus Syrup", "category": "Constipation & Laxative", "manufacturer": "Abbott India", "mrp": 275, "price": 228, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 225ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_048", "name": "Duphalac Oral Solution", "category": "Gentle Laxative", "manufacturer": "Abbott Healthcare", "mrp": 310, "price": 258, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 150ml (Lactulose solution)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_049", "name": "Pudina Hara Active Pearls", "category": "Herbal Digestive", "manufacturer": "Dabur India", "mrp": 30, "price": 25, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 pearls", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_050", "name": "Electral ORS Powder (Orange)", "category": "Energy & Rehydration", "manufacturer": "FDC Limited", "mrp": 24, "price": 20, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 sachet of 21.8g (WHO formula)", "inStock": True, "deliveryMins": 10, "icon": "💧"},
    {"id": "med_051", "name": "Sporlac-DS Tablet", "category": "Probiotic & Gut Health", "manufacturer": "Sanzyme Biogen", "mrp": 110, "price": 89, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 20 tablets (Lactic Acid Bacillus)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_052", "name": "Econorm 250mg Sachet", "category": "Diarrhea & Probiotics", "manufacturer": "Dr. Reddy's Lab", "mrp": 48, "price": 39, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 sachet (Saccharomyces boulardii)", "inStock": True, "deliveryMins": 10, "icon": "💧"},
    {"id": "med_053", "name": "Aciloc 150 Tablet", "category": "Acidity & Heartburn", "manufacturer": "Cadila Pharma", "mrp": 38, "price": 31, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 30 tablets (Ranitidine / Famotidine)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_054", "name": "Sompraz D 40 Capsule", "category": "Acidity & Reflux", "manufacturer": "Sun Pharma", "mrp": 195, "price": 158, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 capsules (Esomeprazole + Domperidone)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_055", "name": "Nexpro 40 Tablet", "category": "Severe Ulcer & Acid", "manufacturer": "Torrent Pharma", "mrp": 160, "price": 129, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Esomeprazole 40mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_056", "name": "Dulcoflex 5mg Tablet", "category": "Laxative", "manufacturer": "Sanofi India", "mrp": 14, "price": 11, "discount": "21% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Bisacodyl 5mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_057", "name": "Gas-O-Fast Active Jeera", "category": "Acidity Sachet", "manufacturer": "Mankind Pharma", "mrp": 10, "price": 8, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 sachet of 5g", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_058", "name": "Gaviscon Liquid (Peppermint)", "category": "Heartburn & Reflux", "manufacturer": "Reckitt Benckiser", "mrp": 190, "price": 159, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 150ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},

    # ------------------------------------------------------------------------
    # 4. DIABETES CARE & GLYCEMIC CONTROL (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_059", "name": "Glycomet GP 1 Tablet", "category": "Diabetes Care", "manufacturer": "USV Pvt Ltd", "mrp": 115, "price": 92, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Metformin 500mg + Glimepiride 1mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_060", "name": "Glycomet GP 2 Tablet", "category": "Diabetes Care", "manufacturer": "USV Pvt Ltd", "mrp": 165, "price": 132, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Metformin 500mg + Glimepiride 2mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_061", "name": "Janumet 50mg/500mg", "category": "Diabetes Care", "manufacturer": "MSD Pharma", "mrp": 380, "price": 315, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Sitagliptin + Metformin)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_062", "name": "Galvus Met 50/500mg", "category": "Diabetes Care", "manufacturer": "Novartis India", "mrp": 420, "price": 348, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Vildagliptin + Metformin)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_063", "name": "Glycomet 500mg SR", "category": "Diabetes Care", "manufacturer": "USV Pvt Ltd", "mrp": 55, "price": 44, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 20 tablets (Metformin SR)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_064", "name": "Teneligliptin 20mg (Zita Plus)", "category": "Diabetes Care", "manufacturer": "Glenmark Pharma", "mrp": 110, "price": 88, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_065", "name": "Rybelsus 3mg Tablet", "category": "Advanced Diabetes Care", "manufacturer": "Novo Nordisk", "mrp": 3200, "price": 2750, "discount": "14% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Oral Semaglutide)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_066", "name": "Amaryl 1mg Tablet", "category": "Diabetes Care", "manufacturer": "Sanofi India", "mrp": 85, "price": 68, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Glimepiride 1mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_067", "name": "Jardiance 10mg Tablet", "category": "Diabetes & Cardio Guard", "manufacturer": "Boehringer Ingelheim", "mrp": 615, "price": 510, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Empagliflozin 10mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_068", "name": "Forxiga 10mg Tablet", "category": "Diabetes & Kidney Care", "manufacturer": "AstraZeneca", "mrp": 720, "price": 599, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 14 tablets (Dapagliflozin 10mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_069", "name": "Trajenta 5mg Tablet", "category": "Diabetes Care", "manufacturer": "Boehringer Ingelheim", "mrp": 680, "price": 565, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Linagliptin 5mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_070", "name": "Glynase XL 5mg", "category": "Diabetes Care", "manufacturer": "USV Pvt Ltd", "mrp": 45, "price": 36, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Glipizide 5mg)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_071", "name": "Accu-Chek Active 50 Strips", "category": "Blood Glucose Strips", "manufacturer": "Roche Diabetes", "mrp": 1050, "price": 845, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 box of 50 test strips", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_072", "name": "OneTouch Select Plus 50 Strips", "category": "Blood Glucose Strips", "manufacturer": "LifeScan J&J", "mrp": 1150, "price": 920, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 box of 50 strips", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_073", "name": "Lantus Solostar Insulin Pen", "category": "Basal Insulin", "manufacturer": "Sanofi India", "mrp": 720, "price": 610, "discount": "15% OFF", "prescriptionRequired": True, "dosage": "1 prefilled pen of 3ml (Insulin Glargine 100IU/ml)", "inStock": True, "deliveryMins": 10, "icon": "💉"},
    {"id": "med_074", "name": "Mixtard 30/70 FlexPen", "category": "Human Insulin", "manufacturer": "Novo Nordisk", "mrp": 580, "price": 490, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 pen of 3ml (30% soluble + 70% isophane)", "inStock": True, "deliveryMins": 10, "icon": "💉"},
    {"id": "med_075", "name": "Glucored Forte Tablet", "category": "Diabetes Care", "manufacturer": "Sun Pharma", "mrp": 120, "price": 98, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_076", "name": "Voglibose 0.3mg (Volibo)", "category": "Post-Meal Glucose", "manufacturer": "Sun Pharma", "mrp": 105, "price": 85, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_077", "name": "Pioglitazone 15mg (Pioz 15)", "category": "Insulin Sensitizer", "manufacturer": "USV Pvt Ltd", "mrp": 75, "price": 60, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_078", "name": "BD Ultra-Fine Insulin Needles", "category": "Insulin Needles (4mm)", "manufacturer": "Becton Dickinson", "mrp": 210, "price": 175, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 box of 100 pen needles (32G)", "inStock": True, "deliveryMins": 10, "icon": "💉"},

    # ------------------------------------------------------------------------
    # 5. CARDIOLOGY, BLOOD PRESSURE & CHOLESTEROL (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_079", "name": "Telmisartan 40mg (Telma 40)", "category": "Cardiac & Blood Pressure", "manufacturer": "Glenmark Pharma", "mrp": 140, "price": 112, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Telmisartan 40mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_080", "name": "Telma-H Tablet", "category": "Cardiac & Blood Pressure", "manufacturer": "Glenmark Pharma", "mrp": 185, "price": 148, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Telmisartan + Hydrochlorothiazide)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_081", "name": "Amlodac 5mg Tablet", "category": "Cardiac & Blood Pressure", "manufacturer": "Zydus Cadila", "mrp": 42, "price": 34, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Amlodipine 5mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_082", "name": "Atorva 10mg Tablet", "category": "Cholesterol & Lipid Care", "manufacturer": "Zydus Cadila", "mrp": 98, "price": 79, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Atorvastatin 10mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_083", "name": "Rosuvas 10mg Tablet", "category": "Cholesterol & Lipid Care", "manufacturer": "Sun Pharma", "mrp": 195, "price": 156, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Rosuvastatin 10mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_084", "name": "Concor 5mg Tablet", "category": "Heart Rate & BP", "manufacturer": "Merck Ltd", "mrp": 125, "price": 102, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Bisoprolol 5mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_085", "name": "Ecosprin 75 Tablet", "category": "Blood Thinner & Antiplatelet", "manufacturer": "USV Pvt Ltd", "mrp": 18, "price": 14, "discount": "22% OFF", "prescriptionRequired": True, "dosage": "1 strip of 14 tablets (Aspirin 75mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_086", "name": "Clopilet 75mg Tablet", "category": "Antiplatelet & Stroke Guard", "manufacturer": "Sun Pharma", "mrp": 120, "price": 98, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Clopidogrel 75mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_087", "name": "Cilacar 10mg Tablet", "category": "Cardiac & Blood Pressure", "manufacturer": "J.B. Chemicals", "mrp": 115, "price": 92, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Cilnidipine 10mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_088", "name": "Met XL 25mg Tablet", "category": "Beta Blocker & BP", "manufacturer": "Ajanta Pharma", "mrp": 78, "price": 63, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Metoprolol Succinate)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_089", "name": "Nebicard 5mg Tablet", "category": "BP & Heart Rate", "manufacturer": "Torrent Pharma", "mrp": 150, "price": 122, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Nebivolol 5mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_090", "name": "Sorbitrate 5mg Tablet", "category": "Angina Chest Pain Relief", "manufacturer": "Abbott India", "mrp": 45, "price": 36, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 50 tablets (Isosorbide Dinitrate)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_091", "name": "Cardace 5mg Tablet", "category": "Cardiac & Blood Pressure", "manufacturer": "Sanofi India", "mrp": 140, "price": 114, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Ramipril 5mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_092", "name": "Arkamin 100mcg Tablet", "category": "High BP Emergency", "manufacturer": "Torrent Pharma", "mrp": 55, "price": 45, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 30 tablets (Clonidine 100mcg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_093", "name": "Dytor 10mg Tablet", "category": "Diuretic & Swelling", "manufacturer": "Cipla Ltd", "mrp": 62, "price": 50, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Torsemide 10mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_094", "name": "Lasix 40mg Tablet", "category": "Diuretic & Edema", "manufacturer": "Sanofi India", "mrp": 15, "price": 12, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Furosemide 40mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_095", "name": "Lipaglyn 4mg Tablet", "category": "Triglycerides & Sugar", "manufacturer": "Zydus Cadila", "mrp": 280, "price": 235, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Saroglitazar)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_096", "name": "Angispan-TR 2.5mg", "category": "Angina Prophylaxis", "manufacturer": "USV Pvt Ltd", "mrp": 210, "price": 172, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 25 capsules (Nitroglycerin)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_097", "name": "Brilinta 90mg Tablet", "category": "Post-Stent Antiplatelet", "manufacturer": "AstraZeneca", "mrp": 950, "price": 799, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 strip of 14 tablets (Ticagrelor 90mg)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},
    {"id": "med_098", "name": "Pradaxa 110mg Capsule", "category": "Anticoagulant Blood Thinner", "manufacturer": "Boehringer Ingelheim", "mrp": 890, "price": 745, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 capsules (Dabigatran)", "inStock": True, "deliveryMins": 10, "icon": "❤️"},

    # ------------------------------------------------------------------------
    # 6. RESPIRATORY, ASTHMA & COLD/COUGH (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_099", "name": "Montair-LC Tablet", "category": "Allergy & Asthma", "manufacturer": "Cipla Ltd", "mrp": 215, "price": 172, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Montelukast + Levocetirizine)", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_100", "name": "Allegra 120mg Tablet", "category": "Allergy & Itch Relief", "manufacturer": "Sanofi India", "mrp": 185, "price": 149, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Fexofenadine 120mg)", "inStock": True, "deliveryMins": 10, "icon": "🤧"},
    {"id": "med_101", "name": "Cetzine 10mg Tablet", "category": "Cold & Runny Nose", "manufacturer": "Dr. Reddy's Lab", "mrp": 22, "price": 17, "discount": "22% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Cetirizine 10mg)", "inStock": True, "deliveryMins": 10, "icon": "🤧"},
    {"id": "med_102", "name": "Asthalin Inhaler (100mcg)", "category": "Asthma Emergency Inhaler", "manufacturer": "Cipla Ltd", "mrp": 150, "price": 128, "discount": "15% OFF", "prescriptionRequired": True, "dosage": "200 metered actuations (Salbutamol)", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_103", "name": "Foracort 200 Inhaler", "category": "Asthma & COPD Maintenance", "manufacturer": "Cipla Ltd", "mrp": 385, "price": 319, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "120 metered doses (Budesonide + Formoterol)", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_104", "name": "Budecort 200 Inhaler", "category": "Asthma Steroid Inhaler", "manufacturer": "Cipla Ltd", "mrp": 260, "price": 218, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "200 doses (Budesonide 200mcg)", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_105", "name": "Ascoril-D Plus Syrup", "category": "Dry Cough & Cold Syrup", "manufacturer": "Glenmark Pharma", "mrp": 125, "price": 104, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml syrup", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_106", "name": "Ascoril-LS Syrup", "category": "Wet Cough & Phlegm", "manufacturer": "Glenmark Pharma", "mrp": 115, "price": 95, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml (Levosalbutamol + Ambroxol)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_107", "name": "Benadryl Cough Formula", "category": "Cough Relief Syrup", "manufacturer": "J&J Consumer", "mrp": 110, "price": 94, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_108", "name": "Otrivin Oxy Fast Relief", "category": "Nasal Spray (Congestion)", "manufacturer": "GSK Healthcare", "mrp": 98, "price": 82, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 spray bottle of 10ml", "inStock": True, "deliveryMins": 10, "icon": "👃"},
    {"id": "med_109", "name": "Solspre Saline Nasal Spray", "category": "Gentle Saline Wash", "manufacturer": "Sun Pharma", "mrp": 140, "price": 118, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 spray bottle of 75ml", "inStock": True, "deliveryMins": 10, "icon": "👃"},
    {"id": "med_110", "name": "Vicks VapoRub 50ml", "category": "Cold & Congestion", "manufacturer": "P&G Healthcare", "mrp": 135, "price": 118, "discount": "13% OFF", "prescriptionRequired": False, "dosage": "1 jar of 50ml", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_111", "name": "Vicks Inhaler Keyring", "category": "Fast Nasal Clearing", "manufacturer": "P&G Healthcare", "mrp": 65, "price": 55, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "Pocket inhaler unit", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_112", "name": "Strepsils Honey & Lemon", "category": "Sore Throat Lozenges", "manufacturer": "Reckitt Benckiser", "mrp": 40, "price": 34, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 blister of 8 lozenges", "inStock": True, "deliveryMins": 10, "icon": "🍬"},
    {"id": "med_113", "name": "Koflet Lozenges (Ginger)", "category": "Ayurvedic Cough Pastilles", "manufacturer": "Himalaya Wellness", "mrp": 35, "price": 30, "discount": "14% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 lozenges", "inStock": True, "deliveryMins": 10, "icon": "🍬"},
    {"id": "med_114", "name": "Grilinctus Cough Syrup", "category": "Cough Syrup", "manufacturer": "Franco-Indian Pharma", "mrp": 112, "price": 94, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_115", "name": "Duolin Respules", "category": "Nebulization Solution", "manufacturer": "Cipla Ltd", "mrp": 180, "price": 149, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 pack of 5 respules (Levosalbutamol + Ipratropium)", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_116", "name": "Budecort 0.5mg Respules", "category": "Nebulization Steroid", "manufacturer": "Cipla Ltd", "mrp": 195, "price": 162, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 pack of 5 respules", "inStock": True, "deliveryMins": 10, "icon": "🫁"},
    {"id": "med_117", "name": "Sinarest Tablet", "category": "Head Cold & Sinus", "manufacturer": "Centaur Pharma", "mrp": 75, "price": 62, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Paracetamol + Phenylephrine)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_118", "name": "Cheston Cold Tablet", "category": "Cold & Sneezing Relief", "manufacturer": "Cipla Ltd", "mrp": 58, "price": 47, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "💊"},

    # ------------------------------------------------------------------------
    # 7. VITAMINS, MINERALS & IMMUNITY (20 items)
    # ------------------------------------------------------------------------
    {"id": "med_119", "name": "Shelcal 500 Calcium Tablet", "category": "Vitamins & Calcium", "manufacturer": "Torrent Pharma", "mrp": 145, "price": 118, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 15 tablets (Calcium 500mg + Vit D3)", "inStock": True, "deliveryMins": 10, "icon": "🦴"},
    {"id": "med_120", "name": "Neurobion Forte Tablet", "category": "Vitamins & Supplements", "manufacturer": "Procter & Gamble", "mrp": 42, "price": 35, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 strip of 30 tablets (Vitamin B-Complex)", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_121", "name": "Becosules Z Capsule", "category": "B-Complex & Zinc", "manufacturer": "Pfizer Ltd", "mrp": 52, "price": 42, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 20 capsules", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_122", "name": "Limcee 500 Chewable", "category": "Vitamin C Immunity", "manufacturer": "Abbott Healthcare", "mrp": 26, "price": 21, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 chewable tablets (Ascorbic Acid)", "inStock": True, "deliveryMins": 10, "icon": "🍊"},
    {"id": "med_123", "name": "Supradyn Daily Multivitamin", "category": "Multivitamin & Minerals", "manufacturer": "Bayer India", "mrp": 60, "price": 49, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_124", "name": "Zincovit Tablet", "category": "Multivitamin with Zinc", "manufacturer": "Apex Laboratories", "mrp": 115, "price": 95, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_125", "name": "Uprise-D3 60K Capsule", "category": "High Potency Vitamin D3", "manufacturer": "Alkem Laboratories", "mrp": 125, "price": 99, "discount": "21% OFF", "prescriptionRequired": False, "dosage": "1 strip of 4 softgel capsules (60,000 IU)", "inStock": True, "deliveryMins": 10, "icon": "☀️"},
    {"id": "med_126", "name": "Calcirol 60K Sachet", "category": "Vitamin D3 Granules", "manufacturer": "Cadila Pharma", "mrp": 45, "price": 38, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 sachet of 1g granules", "inStock": True, "deliveryMins": 10, "icon": "☀️"},
    {"id": "med_127", "name": "Orofer-XT Tablet", "category": "Iron & Hemoglobin", "manufacturer": "Emcure Pharma", "mrp": 195, "price": 158, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets (Ferrous Ascorbate + Folic Acid)", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_128", "name": "Autrin Capsule", "category": "Hematinic & Blood Booster", "manufacturer": "Pfizer Ltd", "mrp": 180, "price": 149, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 30 capsules", "inStock": True, "deliveryMins": 10, "icon": "🩸"},
    {"id": "med_129", "name": "Revital H Daily Capsule", "category": "Ginseng Energy & Stamina", "manufacturer": "Sun Pharma", "mrp": 310, "price": 258, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 30 softgels", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_130", "name": "Evion 400 Vitamin E", "category": "Skin & Hair Vitamin", "manufacturer": "P&G Healthcare", "mrp": 38, "price": 31, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 capsules (Tocopheryl Acetate)", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_131", "name": "Folvite 5mg Tablet", "category": "Folic Acid Supplement", "manufacturer": "Pfizer Ltd", "mrp": 75, "price": 62, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 45 tablets (Folic Acid)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_132", "name": "Maxirich Daily Multivitamin", "category": "Antioxidant & Minerals", "manufacturer": "Cipla Ltd", "mrp": 120, "price": 99, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 softgels", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_133", "name": "Ostocalcium Total Chewable", "category": "Calcium for Adults & Kids", "manufacturer": "GlaxoSmithKline", "mrp": 180, "price": 152, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 30 chewable tablets", "inStock": True, "deliveryMins": 10, "icon": "🦴"},
    {"id": "med_134", "name": "Seven Seas Cod Liver Oil", "category": "Omega-3 & Vitamin A/D", "manufacturer": "P&G Healthcare", "mrp": 360, "price": 305, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100 softgels", "inStock": True, "deliveryMins": 10, "icon": "🐟"},
    {"id": "med_135", "name": "Celin 500mg Tablet", "category": "Vitamin C Supplement", "manufacturer": "Khandelwal Lab", "mrp": 40, "price": 32, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 strip of 25 tablets", "inStock": True, "deliveryMins": 10, "icon": "🍊"},
    {"id": "med_136", "name": "A to Z NS Tablet", "category": "Multivitamins with Minerals", "manufacturer": "Alkem Laboratories", "mrp": 125, "price": 102, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_137", "name": "Cobadex CZS Tablet", "category": "B-Complex, Vit C & Zinc", "manufacturer": "GlaxoSmithKline", "mrp": 60, "price": 49, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 strip of 15 tablets", "inStock": True, "deliveryMins": 10, "icon": "⚡"},
    {"id": "med_138", "name": "Himalaya Liv.52 DS", "category": "Liver Protection & Appetite", "manufacturer": "Himalaya Wellness", "mrp": 195, "price": 165, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 60 tablets", "inStock": True, "deliveryMins": 10, "icon": "🌿"},

    # ------------------------------------------------------------------------
    # 8. DERMATOLOGY & SKINCARE (18 items)
    # ------------------------------------------------------------------------
    {"id": "med_139", "name": "Betnovate-N Cream", "category": "Skin Infection & Eczema", "manufacturer": "GSK Healthcare", "mrp": 55, "price": 45, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 tube of 20g (Betamethasone + Neomycin)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_140", "name": "Candid-B Cream", "category": "Fungal Infection & Rash", "manufacturer": "Glenmark Pharma", "mrp": 145, "price": 122, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 tube of 20g (Clotrimazole + Beclomethasone)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_141", "name": "Fourderm Cream", "category": "Mixed Skin Infection", "manufacturer": "Cipla Ltd", "mrp": 115, "price": 95, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 tube of 15g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_142", "name": "Soframycin Skin Cream", "category": "Wounds, Cuts & Burns", "manufacturer": "Sanofi India", "mrp": 62, "price": 51, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 tube of 30g (Framycetin 1%)", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_143", "name": "T-Bact 2% Ointment", "category": "Bacterial Boils & Impetigo", "manufacturer": "GSK Pharmaceuticals", "mrp": 135, "price": 112, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 tube of 7.5g (Mupirocin 2%)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_144", "name": "Deriva-CMS Gel", "category": "Acne & Pimples", "manufacturer": "Glenmark Pharma", "mrp": 340, "price": 285, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 tube of 15g (Adapalene + Clindamycin)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_145", "name": "Caladryl Skin Lotion", "category": "Prickly Heat & Insect Bites", "manufacturer": "Piramal Healthcare", "mrp": 110, "price": 94, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 120ml (Calamine lotion)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_146", "name": "Burnol Antiseptic Cream", "category": "Burns & Scalds", "manufacturer": "Dr. Morepen", "mrp": 85, "price": 72, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 tube of 20g", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_147", "name": "Ketocip 2% Shampoo", "category": "Anti-Dandruff & Flakes", "manufacturer": "Cipla Ltd", "mrp": 210, "price": 175, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml (Ketoconazole 2%)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_148", "name": "Selsun Anti-Dandruff 120ml", "category": "Medicated Scalp Care", "manufacturer": "Abbott India", "mrp": 310, "price": 260, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 120ml (Selenium Sulfide 2.5%)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_149", "name": "Moiz Cleansing Lotion", "category": "Sensitive Skin Cleanser", "manufacturer": "Glowderma Lab", "mrp": 220, "price": 185, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 200ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_150", "name": "Cetaphil Gentle Cleanser", "category": "Dermatologist Cleanser", "manufacturer": "Galderma India", "mrp": 330, "price": 285, "discount": "14% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 125ml", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_151", "name": "Elovera Moisturizing Cream", "category": "Dry Skin & Eczema", "manufacturer": "Glenmark Pharma", "mrp": 275, "price": 235, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 tube of 150g (Aloe Vera + Vit E)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_152", "name": "Vicco Turmeric Skin Cream", "category": "Ayurvedic Healer", "manufacturer": "Vicco Laboratories", "mrp": 125, "price": 108, "discount": "14% OFF", "prescriptionRequired": False, "dosage": "1 tube of 50g", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_153", "name": "Boroline Antiseptic Cream", "category": "Winter Care & Cracked Heels", "manufacturer": "GD Pharmaceuticals", "mrp": 45, "price": 39, "discount": "13% OFF", "prescriptionRequired": False, "dosage": "1 tube of 40g (Kolkata Classic)", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_154", "name": "Ring Guard Plus Cream", "category": "Ringworm & Itch", "manufacturer": "Reckitt Benckiser", "mrp": 60, "price": 51, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 tube of 20g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_155", "name": "Itaspor 100 Capsule", "category": "Oral Antifungal", "manufacturer": "Intas Pharma", "mrp": 180, "price": 145, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 capsules (Itraconazole 100mg)", "inStock": True, "deliveryMins": 10, "icon": "💊"},
    {"id": "med_156", "name": "Sebogel Salicylic Acid Gel", "category": "Acne & Blackheads", "manufacturer": "Apex Laboratories", "mrp": 240, "price": 204, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 tube of 30g", "inStock": True, "deliveryMins": 10, "icon": "🧴"},

    # ------------------------------------------------------------------------
    # 9. EYE & EAR CARE (OPHTHALMIC & ENT) (16 items)
    # ------------------------------------------------------------------------
    {"id": "med_157", "name": "Ciplox Eye/Ear Drops", "category": "Eye & Ear Infection", "manufacturer": "Cipla Ltd", "mrp": 22, "price": 18, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 dropper vial of 10ml (Ciprofloxacin 0.3%)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_158", "name": "Refresh Tears Eye Drops", "category": "Dry Eyes & Screen Strain", "manufacturer": "Allergan India", "mrp": 180, "price": 152, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 10ml (Carboxymethylcellulose 0.5%)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_159", "name": "Moxicip Eye Drops", "category": "Conjunctivitis & Pink Eye", "manufacturer": "Cipla Ltd", "mrp": 140, "price": 115, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 5ml (Moxifloxacin 0.5%)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_160", "name": "Tobrex 0.3% Eye Drops", "category": "Bacterial Eye Infection", "manufacturer": "Novartis / Alcon", "mrp": 195, "price": 162, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 5ml (Tobramycin)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_161", "name": "Systane Ultra Lubricant Drops", "category": "Severe Dry Eye Relief", "manufacturer": "Alcon Laboratories", "mrp": 340, "price": 289, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 10ml", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_162", "name": "Waxsolve Ear Drops", "category": "Ear Wax Dissolver", "manufacturer": "Sun Pharma", "mrp": 95, "price": 79, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 dropper bottle of 10ml", "inStock": True, "deliveryMins": 10, "icon": "👂"},
    {"id": "med_163", "name": "Clearwax Ear Drops", "category": "Hard Ear Wax Relief", "manufacturer": "Cipla Ltd", "mrp": 88, "price": 73, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 dropper bottle of 10ml", "inStock": True, "deliveryMins": 10, "icon": "👂"},
    {"id": "med_164", "name": "Otogesic Ear Drops", "category": "Ear Pain & Swimmer's Ear", "manufacturer": "Alembic Pharma", "mrp": 75, "price": 62, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 dropper bottle of 5ml", "inStock": True, "deliveryMins": 10, "icon": "👂"},
    {"id": "med_165", "name": "Patanjali Drishti Eye Drops", "category": "Herbal Eye Cleanser", "manufacturer": "Patanjali Ayurved", "mrp": 25, "price": 22, "discount": "12% OFF", "prescriptionRequired": False, "dosage": "1 dropper vial of 10ml", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_166", "name": "Itone Eye Drops", "category": "Herbal Cooling Drops", "manufacturer": "Dey's Medical", "mrp": 55, "price": 47, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 10ml (Kolkata Favorite)", "inStock": True, "deliveryMins": 10, "icon": "🌿"},
    {"id": "med_167", "name": "Travatan Eye Drops", "category": "Glaucoma Eye Pressure", "manufacturer": "Novartis / Alcon", "mrp": 620, "price": 525, "discount": "15% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 2.5ml (Travoprost)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_168", "name": "Timolol 0.5% Eye Drops", "category": "Glaucoma Pressure Drop", "manufacturer": "Cipla Ltd", "mrp": 65, "price": 54, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 5ml", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_169", "name": "Olopat Eye Drops", "category": "Allergic Itchy Eyes", "manufacturer": "Sun Pharma", "mrp": 145, "price": 120, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 5ml (Olopatadine)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_170", "name": "Candibiotic Ear Drops", "category": "Fungal & Bacterial Ear", "manufacturer": "Glenmark Pharma", "mrp": 110, "price": 92, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 dropper bottle of 5ml", "inStock": True, "deliveryMins": 10, "icon": "👂"},
    {"id": "med_171", "name": "Genteal Eye Drops", "category": "Severe Corneal Dryness", "manufacturer": "Novartis India", "mrp": 240, "price": 204, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 10ml (Hypromellose)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},
    {"id": "med_172", "name": "Flur Eye Drops", "category": "Eye Redness & Surgery", "manufacturer": "Allergan India", "mrp": 130, "price": 108, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 5ml (Flurbiprofen)", "inStock": True, "deliveryMins": 10, "icon": "👁️"},

    # ------------------------------------------------------------------------
    # 10. NEUROLOGY, BRAIN & PSYCHIATRIC (16 items)
    # ------------------------------------------------------------------------
    {"id": "med_173", "name": "Nexito 10mg Tablet", "category": "Anxiety & Depression", "manufacturer": "Sun Pharma", "mrp": 115, "price": 94, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Escitalopram 10mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_174", "name": "Clonafit 0.5mg Tablet", "category": "Panic & Anxiety", "manufacturer": "Mankind Pharma", "mrp": 45, "price": 36, "discount": "20% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Clonazepam 0.5mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_175", "name": "Vertin 16mg Tablet", "category": "Vertigo & Dizziness", "manufacturer": "Abbott India", "mrp": 240, "price": 198, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Betahistine 16mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_176", "name": "Stugeron 25mg Tablet", "category": "Motion Sickness & Vertigo", "manufacturer": "Janssen / J&J", "mrp": 170, "price": 142, "discount": "16% OFF", "prescriptionRequired": True, "dosage": "1 strip of 25 tablets (Cinnarizine 25mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_177", "name": "Gabapin NT Tablet", "category": "Nerve Pain & Neuropathy", "manufacturer": "Intas Pharma", "mrp": 290, "price": 238, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Gabapentin + Nortriptyline)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_178", "name": "Pregabalin 75mg (Pregalin)", "category": "Diabetic Nerve Pain", "manufacturer": "Torrent Pharma", "mrp": 195, "price": 159, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 capsules", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_179", "name": "Alprax 0.25mg Tablet", "category": "Mild Anxiety & Calmer", "manufacturer": "Torrent Pharma", "mrp": 32, "price": 26, "discount": "19% OFF", "prescriptionRequired": True, "dosage": "1 strip of 15 tablets (Alprazolam)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_180", "name": "Eptoin 100mg Tablet", "category": "Epilepsy & Seizures", "manufacturer": "Abbott India", "mrp": 195, "price": 162, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 bottle of 120 tablets (Phenytoin 100mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_181", "name": "Encorate Chrono 300", "category": "Bipolar & Seizure Control", "manufacturer": "Sun Pharma", "mrp": 120, "price": 99, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Sodium Valproate)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_182", "name": "Sibelium 10mg Tablet", "category": "Migraine Prevention", "manufacturer": "Janssen / J&J", "mrp": 210, "price": 175, "discount": "17% OFF", "prescriptionRequired": True, "dosage": "1 strip of 20 tablets (Flunarizine 10mg)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_183", "name": "Vasograin Tablet", "category": "Acute Migraine Attack", "manufacturer": "Cadila Pharma", "mrp": 95, "price": 78, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 14 tablets (Ergotamine + Caffeine)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_184", "name": "Pacitane 2mg Tablet", "category": "Parkinsonism & Tremors", "manufacturer": "Pfizer Ltd", "mrp": 38, "price": 31, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 30 tablets (Trihexyphenidyl)", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_185", "name": "Piracetam 800mg (Nootropil)", "category": "Memory & Cognitive", "manufacturer": "Dr. Reddy's Lab", "mrp": 190, "price": 155, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_186", "name": "Citicoline 500mg (Stiloz)", "category": "Stroke Recovery & Brain", "manufacturer": "Sun Pharma", "mrp": 480, "price": 395, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🧠"},
    {"id": "med_187", "name": "Melset 3mg Melatonin", "category": "Sleep Cycle Regulation", "manufacturer": "Aristo Pharma", "mrp": 90, "price": 75, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 strip of 10 tablets", "inStock": True, "deliveryMins": 10, "icon": "🌙"},
    {"id": "med_188", "name": "Zolfresh 5mg Tablet", "category": "Insomnia Short-Term", "manufacturer": "Abbott India", "mrp": 85, "price": 70, "discount": "18% OFF", "prescriptionRequired": True, "dosage": "1 strip of 10 tablets (Zolpidem 5mg)", "inStock": True, "deliveryMins": 10, "icon": "🌙"},

    # ------------------------------------------------------------------------
    # 11. FIRST AID, ANTISEPTICS & SURGICAL ESSENTIALS (16 items)
    # ------------------------------------------------------------------------
    {"id": "med_189", "name": "Betadine 10% Solution (100ml)", "category": "Antiseptic Microbicide", "manufacturer": "Win-Medicare", "mrp": 135, "price": 115, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml (Povidone Iodine 10%)", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_190", "name": "Dettol Antiseptic Liquid 250ml", "category": "First Aid & Disinfectant", "manufacturer": "Reckitt Benckiser", "mrp": 160, "price": 138, "discount": "14% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 250ml", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_191", "name": "Savlon Antiseptic Liquid 200ml", "category": "Gentle Antiseptic", "manufacturer": "ITC Limited", "mrp": 120, "price": 102, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 200ml (Chlorhexidine + Cetrimide)", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_192", "name": "Band-Aid Washproof Strips", "category": "Wound Bandages", "manufacturer": "J&J Consumer", "mrp": 55, "price": 45, "discount": "18% OFF", "prescriptionRequired": False, "dosage": "1 pack of 20 strips", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_193", "name": "Hansaplast Medicated Plaster", "category": "Antiseptic Dressing", "manufacturer": "Beiersdorf", "mrp": 60, "price": 50, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 pack of 20 strips", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_194", "name": "Cotton Absorbent Roll 100g", "category": "Sterile Surgical Cotton", "manufacturer": "Bengal Chemicals", "mrp": 65, "price": 54, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 roll of 100g pure cotton", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_195", "name": "Crepe Bandage 10cm (Sprain)", "category": "Joint Elastic Support", "manufacturer": "Flamingo Healthcare", "mrp": 195, "price": 165, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 roll with metal clips", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_196", "name": "Micropore Surgical Tape 1-inch", "category": "Hypoallergenic Tape", "manufacturer": "3M Healthcare", "mrp": 85, "price": 72, "discount": "15% OFF", "prescriptionRequired": False, "dosage": "1 roll of 9.1m", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_197", "name": "Sterile Gauze Swabs (10x10cm)", "category": "Wound Dressing Pads", "manufacturer": "Datt Mediproducts", "mrp": 70, "price": 58, "discount": "17% OFF", "prescriptionRequired": False, "dosage": "1 pack of 10 sterile swabs", "inStock": True, "deliveryMins": 10, "icon": "🩹"},
    {"id": "med_198", "name": "Dr. Morepen Digital Thermometer", "category": "Fever Diagnostic Device", "manufacturer": "Dr. Morepen", "mrp": 250, "price": 199, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "Digital fast-read probe with LCD", "inStock": True, "deliveryMins": 10, "icon": "🌡️"},
    {"id": "med_199", "name": "Fingertip Pulse Oximeter", "category": "Oxygen SpO2 & Pulse", "manufacturer": "Beurer / Dr Trust", "mrp": 1200, "price": 890, "discount": "26% OFF", "prescriptionRequired": False, "dosage": "OLED Dual Color SpO2 Monitor", "inStock": True, "deliveryMins": 10, "icon": "🫀"},
    {"id": "med_200", "name": "Omron HEM-7120 Smart BP Monitor", "category": "Digital Upper Arm BP", "manufacturer": "Omron Healthcare", "mrp": 2450, "price": 1980, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "1 automatic monitor with Intellisense cuff", "inStock": True, "deliveryMins": 10, "icon": "🩺"},
    {"id": "med_201", "name": "Sterillium Hand Rub 100ml", "category": "Hospital Grade Sanitizer", "manufacturer": "Bode Chemie / Raman & Weil", "mrp": 125, "price": 105, "discount": "16% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml (Propanol solution)", "inStock": True, "deliveryMins": 10, "icon": "🧴"},
    {"id": "med_202", "name": "Hydrogen Peroxide 3% 100ml", "category": "Wound Cleanser", "manufacturer": "Bengal Chemicals", "mrp": 35, "price": 28, "discount": "20% OFF", "prescriptionRequired": False, "dosage": "1 bottle of 100ml", "inStock": True, "deliveryMins": 10, "icon": "💧"},
    {"id": "med_203", "name": "Hot Water Rubber Bottle 2L", "category": "Pain Cramp Reliever", "manufacturer": "Flamingo Healthcare", "mrp": 290, "price": 235, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "Leakproof natural rubber bottle", "inStock": True, "deliveryMins": 10, "icon": "🔥"},
    {"id": "med_204", "name": "Ice Bag Cold Pack for Sprains", "category": "Cold Compression Therapy", "manufacturer": "Flamingo Healthcare", "mrp": 220, "price": 178, "discount": "19% OFF", "prescriptionRequired": False, "dosage": "9-inch fabric cold compress bag", "inStock": True, "deliveryMins": 10, "icon": "❄️"}
]
